update to yq v4

diff --git a/deployments/caddy/deploy b/deployments/caddy/deploy
--- a/deployments/caddy/deploy
+++ b/deployments/caddy/deploy
@@ -14,7 +14,12 @@ function get_yaml_value() {
     exit 1
   fi
 
-  "$yq_cli" read "$file" "$key"
+  if [[ "$(yq --version)" != *"version 4"* ]]; then
+    echo "yq v4 is required (found $(yq --version))" >&2
+    exit 12
+  fi
+
+  "$yq_cli" "$key" "$file"
 }
 
 base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"
diff --git a/deployments/concourse/deploy b/deployments/concourse/deploy
--- a/deployments/concourse/deploy
+++ b/deployments/concourse/deploy
@@ -14,7 +14,12 @@ function get_yaml_value() {
     exit 1
   fi
 
-  "$yq_cli" read "$file" "$key"
+  if [[ "$(yq --version)" != *"version 4"* ]]; then
+    echo "yq v4 is required (found $(yq --version))" >&2
+    exit 12
+  fi
+
+  "$yq_cli" "$key" "$file"
 }
 
 base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"
@@ -28,7 +33,7 @@ if [[ ! -d "${repo}/tmp/concourse-bosh-deployment" ]] ; then
 fi
 
 # checkout specific version of concourse-bosh-deployment
-REF="v$(get_yaml_value "${repo}/deployments/concourse/versions.yml" 'concourse_version')"
+REF="v$(get_yaml_value "${repo}/deployments/concourse/versions.yml" '.concourse_version')"
 echo "Checking out to concourse-bosh-deployment to ref: ${REF}"
 
 pushd ${repo}/tmp/concourse-bosh-deployment > /dev/null
