bump bosh to 280.1.17

diff --git a/environment/bin/create-env b/environment/bin/create-env
--- a/environment/bin/create-env
+++ b/environment/bin/create-env
@@ -20,12 +20,24 @@ set -euo pipefail
 #
 #   $ ./bin/create-env
 
-base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"
-repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"
+base="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
+repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
+
+export BOSHOPS_vcenter_user=
+if ! BOSHOPS_vcenter_user=$(credhub get -n /cloud/vcenter -k username); then
+  echo "Failed to retrieve /cloud/vcenter username" >&2
+  exit 1
+fi
+
+export BOSHOPS_vcenter_password=
+if ! BOSHOPS_vcenter_password=$(credhub get -n /cloud/vcenter -k password); then
+  echo "Failed to retrieve /cloud/vcenter password" >&2
+  exit 1
+fi
 
 echo "Deploying BOSH"
 bosh create-env --vars-env BOSHOPS \
   --state "${base}/bosh-secrets/bosh/state.json" \
   --vars-store "${base}/bosh-secrets/bosh/creds.yml" \
-  --vars-file  "${base}/bosh-secrets/vars.yml" \
+  --vars-file "${base}/bosh-secrets/vars.yml" \
   "${repo}/environment/bosh.yml"
